version: "3.8"

services:
  client:
    build:
      context: ./client

    command:
      - npm
      - start

    ports:
      - "3000:3000"

    environment:
      - REACT_APP_AUTH0_DOMAIN=
      - REACT_APP_AUTH0_CLIENT_ID=

  custom_assets:
    build:
      context: ./custom_assets

    command:
      - python
      - manage.py
      - runserver
      - 0.0.0.0:8000

    ports:
      - "8000:8000"

    environment:
      - db-name=
      - db-host=
      - db-user=
      - db-password=

  assets:
    build:
      context: ./assets

    command:
      - flask
      - run
      - --host=0.0.0.0

    ports:
      - "5000:5000"

    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=development
      - YODLEE_CLIENT_ID=
      - YODLEE_SECRET=
      - YODLEE_SANDBOX_URL=
      - nordigen_token=

  portfolio:
    build:
      context: ./portfolio

    command:
      - flask
      - run
      - --host=0.0.0.0
      - --port=5001

    ports:
      - "5001:5001"

    environment:
      - FLASK_APP=portfolio
      - FLASK_ENV=development
      - REFERENCE_URL=
      - ASSETS_URL=
      - ACCOUNT_URL=