version: "3.8"

services:
  client:
    build:
      context: ./client

    command:
      - npm
      - start

    ports:
      - "3000:3000"

    env_file:
      - data.env

  custom-assets:
    build:
      context: ./custom_assets

    command:
      - python
      - manage.py
      - runserver
      - 0.0.0.0:8000

    ports:
      - "8000:8000"

    env_file:
      - data.env

  assets:
    build:
      context: ./assets

    command:
      - flask
      - run
      - --host=0.0.0.0

    ports:
      - "5000:5000"

    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=development

    env_file:
      - data.env

  portfolio:
    build:
      context: ./portfolio

    command:
      - flask
      - run
      - --host=0.0.0.0
      - --port=5001

    ports:
      - "5001:5001"

    environment:
      - FLASK_APP=portfolio
      - FLASK_ENV=development
      - REFERENCE_URL=http://reference:5002/
      - ASSETS_URL=http://assets:5000/
      - ACCOUNT_URL=http://account:8001/

  reference:
    build:
      context: ./reference

    command:
      - flask
      - run
      - --host=0.0.0.0
      - --port=5002

    ports:
      - "5002:5002"

    environment:
      - FLASK_APP=reference
      - FLASK_ENV=development
      - TD_API_KEY=
      - CL_API_KEY=

  account:
    build:
      context: ./account/account

    command:
      - python
      - manage.py
      - runserver
      - 0.0.0.0:8001

    ports:
      - "8001:8001"

    environment:
      - FIELD_ENCRYPTION_KEY=
      - DB_HOST=
      - DB_USERNAME=
      - DB_PASSWORD=
      - JWT_AUDIENCE=
      - JWT_ISSUER=
      - DELETE_USER=
      - MANAGER_TOKEN_PAYLOAD=
      - MANAGER_TOKEN_URL=
