version: "3.8"

services:
  custom_assets:
    build:
      context: ./custom_assets
    command:
      - python
      - manage.py
      - runserver
      - 0.0.0.0:8000
    ports:
      - "8000:8000"

    environment:
      - db-name=
      - db-host=
      - db-user=
      - db-password=
