# Generated by Django 3.1.12 on 2021-10-13 16:36

import api.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_key', models.CharField(max_length=500)),
                ('crypto_assets', djongo.models.fields.ArrayField(model_container=api.models.CryptoAsset)),
                ('stock_assets', djongo.models.fields.ArrayField(model_container=api.models.StockAsset)),
                ('currency_assets', djongo.models.fields.ArrayField(model_container=api.models.CurrencyAsset)),
            ],
        ),
    ]
