# Generated by Django 3.2.9 on 2021-12-06 09:50

import balance_caching_app.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('balance', models.FloatField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('source_balances_history', djongo.models.fields.ArrayField(model_container=balance_caching_app.models.Source)),
            ],
            options={
                'ordering': ['timestamp'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('provider', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('value', models.FloatField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(max_length=500)),
                ('last_login', models.DateTimeField()),
                ('balances_history', djongo.models.fields.ArrayField(model_container=balance_caching_app.models.Balance)),
            ],
        ),
    ]
