# Generated by Django 3.2.9 on 2021-11-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_accounts', models.IntegerField(default=0)),
                ('total_assets_on_platform', models.FloatField(default=0)),
            ],
        ),
    ]
