# Generated by Django 3.2.9 on 2021-11-09 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Monitor',
        ),
    ]
