# Generated by Django 3.2.8 on 2021-10-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_assets_key', models.CharField(max_length=50)),
                ('crypto', models.CharField(max_length=5)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
