# Generated by Django 3.2.7 on 2021-10-13 07:31

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('user_identifier', models.CharField(max_length=40)),
                ('base_currency', models.CharField(default='GBP', max_length=5)),
                ('source_label', models.CharField(blank=True, max_length=20)),
                ('binance_key', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('binance_secret', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('coinbase_api_secret', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('coinbase_api_key', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('coinbase_api_pass', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('yodlee_login_name', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('nordigen_requisition', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('custom_assets_key', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
            ],
        ),
    ]
