# Generated by Django 3.2.8 on 2021-10-31 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='custom_assets_key',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='yodlee_login_name',
        ),
        migrations.AlterField(
            model_name='nordigenrequisition',
            name='institution_id',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nordigenrequisition',
            name='requisition_id',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
    ]
