# Generated by Django 3.2.8 on 2021-11-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20211031_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='nordigenrequisition',
            name='confirmation_link',
            field=models.URLField(default='https://www.google.com', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nordigenrequisition',
            name='institution_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nordigenrequisition',
            name='requisition_id',
            field=models.CharField(max_length=100),
        ),
    ]
