# Generated by Django 3.2.8 on 2021-11-04 08:28

from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('user_identifier', models.CharField(max_length=40)),
                ('base_currency', models.CharField(default='GBP', max_length=5)),
                ('source_label', models.CharField(blank=True, max_length=20)),
                ('binance_key', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('binance_secret', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('coinbase_api_secret', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('coinbase_api_key', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NordigenRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_id', models.CharField(max_length=100)),
                ('requisition_id', encrypted_model_fields.fields.EncryptedCharField()),
                ('confirmation_link', encrypted_model_fields.fields.EncryptedCharField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
            ],
        ),
    ]
